abstract: Objects that represent generic computational processes
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
build_requires: 
  File::Remove: 0
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Process
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::Temp: 0
  IO::File: 0
  IO::Handle: 0
  IO::String: 0
  IPC::Run3: 0.034
  Params::Util: 0.10
  Scalar::Util: 1.17
  Storable: 2.14
  perl: 5.005
version: 0.18
