
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.54
distribution_type: module
version: 0.15
name: Process
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  File::Remove: 0
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.17
  IO::File: 0
  IO::String: 0
  IO::Handle: 0
  Storable: 2.14
  perl: 5.005
  Params::Util: 0.10
  File::Temp: 0
  IPC::Run3: 0.034
abstract: Objects that represent generic computational processes
